name: untitled
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies:
  encrypt: ^5.0.1
  convert: ^3.0.1
  crypto: ^3.0.2
  cryptography: ^2.0.5
  rsa_encrypt: ^2.0.0
